import {SortButton,sortRows,useTableSort} from './TableSort';
import StudentName from './StudentName';
import { sourceCriterionId, criterionRubric, preserveLegacyCriterionGrades } from '../utils/activityCriteria';
import React, { useState } from 'react';
import { AppState, CurricularActivity, Subject, StudentActivityGrade } from '../types';
import DetailPage from './DetailPage';
import { GradeBadge, GradeButtons } from './GradeControls';
import { getActivityScore, getCriterionScore, getCompSettings, scoreToCompetencial, exportActivitiesToExcel } from '../utils/gradeCalculations';

export default function ActivityGradePage({state,activity,subject,onChange,onBack}:{state:AppState;activity:CurricularActivity;subject:Subject;onChange:(s:AppState)=>void;onBack:()=>void}) {
  const [search,setSearch]=useState('');
  const {sort,toggle}=useTableSort();
  const settings=getCompSettings(subject), students=sortRows(subject.students.filter(s=>s.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())),sort,s=>s.name);
  const criteria=activity.criteriaIds || [];
  const update=(studentId:string,fn:(g:StudentActivityGrade)=>StudentActivityGrade)=>{
    const prepared=preserveLegacyCriterionGrades(activity);
    const grades={...prepared,[studentId]:fn(prepared[studentId] || {})};
    onChange({...state,activities:(state.activities||[]).map(a=>a.id===activity.id?{...a,grades}:a)});
  };
  const clear=()=>{if(window.confirm('Esborrar totes les notes i comentaris d’aquesta activitat?')) onChange({...state,activities:(state.activities||[]).map(a=>a.id===activity.id?{...a,grades:{}}:a)});};
  return <DetailPage title={`Avaluar · ${activity.code}`} subtitle={`${activity.title} · ${subject.name}`} onBack={onBack} actions={<><span className="text-sm text-slate-500 self-center">Desat automàtic</span><button className="ds-button" onClick={()=>exportActivitiesToExcel(subject,[activity],state.criteria,subject.students)}>Exportar Excel</button><button className="ds-button text-rose-700" onClick={clear}>Esborrar notes</button></>}>
    <div className="ds-panel flex flex-wrap justify-between gap-3 items-center"><input aria-label="Cercar alumne" placeholder="Cercar alumne…" value={search} onChange={e=>setSearch(e.target.value)}/><span className="text-sm text-slate-600">{subject.students.length} alumnes · Lliurament {activity.endDate} · Pes {activity.weight}</span><span className="text-sm">AS ≥ {settings.thresholds.AS} · AN ≥ {settings.thresholds.AN} · AE ≥ {settings.thresholds.AE} /4</span></div>
    <div className="grade-table-wrap"><table className="grade-table"><thead><tr><th aria-sort={sort.direction==='asc'?'ascending':'descending'}><SortButton label="Alumne/a" column="name" sort={sort} onSort={toggle}/></th><th>Criteri / aspecte</th><th>Qualificació</th><th>Activitat</th><th>Comentari de l’alumne</th></tr></thead>
      {students.map((st,index)=>{const g=activity.grades?.[st.id] || {}, rows=criteria.length?criteria:[''], total=getActivityScore(activity,st.id,subject);return <tbody key={st.id} className={`activity-student-group ${index%2?'student-even':'student-odd'}`}>{rows.map((cid,row)=>{
        const cr=state.criteria.find(c=>c.id===sourceCriterionId(activity,cid)), cg=g.criteriaGrades?.[cid], type=cid?(activity.criteriaGradingType?.[cid] || 'competencial'):(activity.numericGradingType || 'numeric'), max=cid?(activity.criteriaMaxScores?.[cid] ?? 10):10;
        const score=cid?getCriterionScore(activity,st.id,cid,subject):total;
        const label=cid?(activity.criteriaCustomLabels?.[cid] || cr?.key || cid):'Nota global';
        return <tr key={cid || 'global'}>{row===0 && <td rowSpan={rows.length} className="student-cell"><span className="text-slate-400 mr-2">{index+1}</span><StudentName state={state} student={st}/><span className="inline-flex gap-1 ml-2" role="group" aria-label={`Estat de l’activitat de ${st.name}`}>{(['not_submitted','exempt'] as const).map(status=><button key={status} type="button" aria-pressed={g.status===status} title={status==='not_submitted'?'No presentat: tots els criteris compten com a 0. Torna a prémer per retirar-ho.':'Exempt: no entra als càlculs. Torna a prémer per retirar-ho.'} onClick={()=>update(st.id,old=>({...old,status:old.status===status?undefined:status}))} className={`px-2 py-1 rounded border text-xs ${g.status===status?(status==='not_submitted'?'bg-black text-white border-black':'bg-slate-600 text-white border-slate-600'):'bg-white text-slate-600 border-slate-300'}`}>{status==='not_submitted'?'NP':'Exempt'}</button>)}</span></td>}<td title={cr?.description}><strong>{label}</strong>{cid && <span className="block text-xs text-slate-500">{cr?.key} · pes {activity.criteriaWeights?.[cid] ?? 1}</span>}</td><td>{g.status?<span className="inline-flex items-center gap-2"><GradeBadge qual={g.status==='not_submitted'?'NP':'Exempt'}/>{g.status==='not_submitted'&&<span className="text-sm">0 /4</span>}</span>:type==='numeric'?<div className="flex items-center gap-2"><input className="score-input" aria-label={`${st.name}: ${label}`} type="number" min="0" max={max} step="0.01" value={cid?cg?.rawScore ?? '':g.score ?? ''} onChange={e=>{const value=e.target.value===''?undefined:Math.max(0,Math.min(max,Number(e.target.value)));if(value===undefined&&!window.confirm(`Esborrar la nota de ${st.name}: ${label}?`))return;update(st.id,old=>{
          if(cid){old.criteriaGrades={...old.criteriaGrades}; if(value===undefined) delete old.criteriaGrades[cid]; else old.criteriaGrades[cid]={criterionId:cid,rawScore:value,maxScore:max};delete old.score;delete old.competencialScore;}else{old.score=value;delete old.competencialScore;}return old;
        });}}/><span className="text-slate-500">/{max}</span>{cid && <span className="inline-flex items-center gap-2 border-l border-slate-300 pl-2 text-sm text-slate-600 whitespace-nowrap" aria-label={`Equivalent sobre 4: ${score===null?'pendent':score.toFixed(2)}`}><span className="tabular-nums">{score===null?'—':score.toFixed(2)} /4</span>{score!==null&&<GradeBadge description={criterionRubric(activity,cid,cr)[scoreToCompetencial(score,settings.thresholds)]} qual={scoreToCompetencial(score,settings.thresholds)}/>}</span>}</div>:<GradeButtons descriptions={criterionRubric(activity,cid,cr)} label={`${st.name}: ${label}`} value={cid?cg?.competencialScore:g.competencialScore} onChange={q=>update(st.id,old=>{if(cid){old.criteriaGrades={...old.criteriaGrades};if(old.criteriaGrades[cid]?.competencialScore===q)delete old.criteriaGrades[cid];else old.criteriaGrades[cid]={criterionId:cid,competencialScore:q};delete old.score;delete old.competencialScore;}else{old.competencialScore=old.competencialScore===q?undefined:q;delete old.score;}return old;})}/>}</td>{row===0 && <><td rowSpan={rows.length}>{g.status?<span className="inline-flex items-center gap-2"><GradeBadge qual={g.status==='not_submitted'?'NP':'Exempt'}/>{g.status==='not_submitted'&&<b>0</b>}</span>:total===null?'—':<div className="space-y-1"><b>{(total*(subject.evaluationType==='numeric'?2.5:1)).toFixed(2)}</b><span className="block"><GradeBadge qual={scoreToCompetencial(total,settings.thresholds)}/></span></div>}</td><td rowSpan={rows.length}><textarea rows={2} aria-label={`Comentari ${st.name}`} placeholder="Comentari…" value={g.comment||''} onChange={e=>update(st.id,old=>({...old,comment:e.target.value}))}/></td></>}</tr>;
      })}</tbody>})}
    </table>{!students.length && <p className="p-6 text-slate-500">No hi ha alumnes per mostrar.</p>}</div>
  </DetailPage>;
}
