import React,{useState} from 'react';
import {AppState} from '../types';
import {activitiesOverview} from '../utils/activityStatus';
import {SortButton,sortRows,useTableSort} from './TableSort';
export default function ActivitiesOverview({state,onOpen}:{state:AppState;onOpen:(id:string)=>void}){
  const [period,setPeriod]=useState('annual'),[search,setSearch]=useState('');
  const {sort,toggle}=useTableSort();
  const rows=sortRows(activitiesOverview(state,period).filter(r=>r.subject.name.toLocaleLowerCase('ca').includes(search.toLocaleLowerCase('ca'))),sort,(r,key)=>key==='name'?r.subject.name:r[key]);
  const columns=[['name','Classe / assignatura'],['total','Total'],['not_open','Pendents d’obrir'],['open','Obertes'],['pending_correction','Pendents de corregir'],['corrected','Corregides'],['inherited','Del grup mare, per importar']];
  return <section className="space-y-4"><header className="page-heading"><div><h2 className="text-xl font-bold">Activitats · Resum de classes</h2><p className="text-sm text-slate-500">Entra a una assignatura per planificar, configurar i qualificar les activitats.</p></div></header><div className="ds-panel flex flex-wrap gap-3"><label className="ds-field flex-1">Buscar classe<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="ds-field">Període<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="annual">Tot el curs</option>{state.config.terms.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div><div className="grade-table-wrap"><table className="grade-table"><thead><tr>{columns.map(([key,label])=><th key={key} aria-sort={sort.key===key?(sort.direction==='asc'?'ascending':'descending'):'none'}><SortButton label={label} column={key} sort={sort} onSort={toggle}/></th>)}<th>Acció</th></tr></thead><tbody>{rows.map(r=><tr key={r.subject.id}><td><button className="text-blue-800 font-semibold" onClick={()=>onOpen(r.subject.id)}>{r.subject.name}</button>{r.subject.isParent&&<span className="block text-xs text-slate-500">Grup mare</span>}</td><td>{r.total}</td><td className="text-slate-600">{r.not_open}</td><td className="text-blue-700">{r.open}</td><td className="text-amber-800">{r.pending_correction}</td><td className="text-emerald-700">{r.corrected}</td><td>{r.inherited}</td><td><button className="ds-button" onClick={()=>onOpen(r.subject.id)}>Obrir dossier</button></td></tr>)}</tbody></table>{!rows.length&&<p className="p-4 text-slate-500">No hi ha classes per mostrar.</p>}</div><p className="text-sm text-slate-500">Els estats corresponen a les activitats pròpies de cada assignatura, segons les dates i l’avaluació, o l’estat fixat manualment. Les activitats del grup mare disponibles per importar es mostren a part. El període es filtra per la data de lliurament.</p></section>;
}
