import React, { useState } from 'react';
import { AppState } from '../types';
import DetailPage from './DetailPage';
import { getCompSettings } from '../utils/gradeCalculations';
export default function ClassesView({state,onNavigateToConfig,onNavigateToPlans}:{state:AppState;onNavigateToConfig:(id?:string)=>void;onNavigateToPlans:()=>void}) {
  const [selected,setSelected]=useState<string|null>(null);
  const subject=state.subjects.find(s=>s.id===selected);
  if(subject){const competencies=state.competencies.filter(c=>c.subjectId===subject.id||c.subjectId===subject.parentId),settings=getCompSettings(subject);return <DetailPage title={subject.name} subtitle={`${subject.students.length} alumnes · ${subject.isGeneral?'Acció general':subject.isParent?'Grup mare':subject.evaluationType==='numeric'?'Avaluació numèrica':'Avaluació competencial'}`} onBack={()=>setSelected(null)} actions={<button className="ds-button ds-primary" onClick={()=>onNavigateToConfig(subject.id)}>Configurar assignatura</button>}><div className="grid lg:grid-cols-2 gap-4"><section className="ds-panel"><h3 className="font-bold mb-3">Alumnat</h3>{subject.students.map((st,i)=><p key={st.id} className="p-2 odd:bg-slate-50 text-sm"><span className="text-slate-400 mr-3">{i+1}</span>{st.name}</p>)}{!subject.students.length&&<p className="text-slate-500">Sense alumnat assignat.</p>}</section><section className="ds-panel space-y-3"><h3 className="font-bold">Avaluació</h3><p className="text-sm">Llindars sobre 4: AS ≥ {settings.thresholds.AS} · AN ≥ {settings.thresholds.AN} · AE ≥ {settings.thresholds.AE}</p>{competencies.map(c=><div key={c.id} className="border-t pt-2"><b>{c.key}</b><p className="text-sm text-slate-600">{c.description}</p></div>)}{(subject.numericItems||[]).map(i=><p key={i.id} className="text-sm">{i.code} · {i.name} · {i.weight}%</p>)}<button className="ds-button" onClick={onNavigateToPlans}>Veure plànols</button></section></div></DetailPage>;}
  return <section className="space-y-4"><header className="page-heading"><div><h2 className="text-xl font-bold">Assignatures</h2><p className="text-sm text-slate-500">{state.subjects.length} grups i accions docents</p></div><button className="ds-button ds-primary" onClick={()=>onNavigateToConfig('new')}>Nova assignatura</button></header><div className="grade-table-wrap"><table className="grade-table"><thead><tr><th>Assignatura</th><th>Grup mare</th><th>Alumnes</th><th>Avaluació</th><th>Accions</th></tr></thead><tbody>{state.subjects.map(s=><tr key={s.id}><td style={{borderLeft:`4px solid ${s.color}`}}><button className="font-semibold text-blue-800 text-left" onClick={()=>setSelected(s.id)}>{s.name}</button></td><td>{state.subjects.find(p=>p.id===s.parentId)?.name||'—'}</td><td>{s.students.length}</td><td>{s.isGeneral?'General':s.isParent?'Grup mare':s.evaluationType==='numeric'?'Numèrica · 0–10':'Competencial · 0–4'}</td><td><div className="flex gap-2"><button className="ds-button" onClick={()=>setSelected(s.id)}>Obrir</button><button className="ds-button" onClick={()=>onNavigateToConfig(s.id)}>Configurar</button></div></td></tr>)}</tbody></table></div></section>;
}
