import { CurriculumTarget } from './CurriculumEditor';
import React from 'react';
import { AppState } from '../types';
export default function CriteriaLabels({state,subjectId,onChange,onEdit}:{state:AppState;subjectId:string;onChange:(s:AppState)=>void;onEdit:(t:CurriculumTarget)=>void}) {
  const ids=state.competencies.filter(c=>c.subjectId===subjectId).map(c=>c.id);
  const criteria=state.criteria.filter(c=>ids.includes(c.competencyId)).sort((a,b)=>(a.order??0)-(b.order??0));
  const move=(index:number,delta:number)=>{const list=[...criteria];[list[index],list[index+delta]]=[list[index+delta],list[index]];onChange({...state,criteria:state.criteria.map(c=>{const i=list.findIndex(x=>x.id===c.id);return i<0?c:{...c,order:i};})});};
  if (!ids.length) return null;
  return <section className="ds-panel space-y-2"><h3 className="font-bold">Editar competències i criteris</h3><div className="space-y-2">{state.competencies.filter(c=>ids.includes(c.id)).map(c=><div className="flex justify-between items-center gap-3 border-b pb-2" key={c.id}><div><b>{c.key}</b><p className="text-sm text-slate-600">{c.description}</p></div><button type="button" className="ds-button" onClick={()=>onEdit({kind:'competency',id:c.id})}>Editar competència</button></div>)}</div><p className="text-sm text-slate-500">El codi identifica el criteri. A cada activitat pots assignar-li un text breu propi.</p>{criteria.map((c,index)=><div key={c.id} className="grid grid-cols-[auto_1fr_auto_auto_auto] items-center gap-2"><span className="font-mono text-sm" title={c.description}>{c.key}</span><span className="text-sm text-slate-600">{c.description}</span><button className="ds-button" type="button" onClick={()=>onEdit({kind:'criterion',id:c.id})}>Editar criteri</button><button className="ds-button" type="button" disabled={index===0} aria-label={`Pujar ${c.key}`} onClick={()=>move(index,-1)}>↑</button><button className="ds-button" type="button" disabled={index===criteria.length-1} aria-label={`Baixar ${c.key}`} onClick={()=>move(index,1)}>↓</button></div>)}</section>;
}
