import React,{useState} from 'react';
import {AppState} from '../types';
import {OrphanItem} from '../utils/orphanData';
import OrphanDataReview from './OrphanDataReview';
import {RecoveryCopy,triggerRawJsonDownload} from '../storage';
type Notice={kind:string;message:string;key:string};
type Props={status:'saved'|'saving'|'error';linkedFileName:string|null;availableName?:string;busy:boolean;canEdit:boolean;notices:Notice[];reviewed:string[];conflicts:string[];copies:RecoveryCopy[];onReview:(key:string)=>void;onRetry:()=>void;onKeepLocal:()=>void;onDiscard:()=>void;onDownload:()=>void;onForget:()=>void;onConnect:()=>void;onKeepCurrent:()=>void;onChooseFile:()=>void;onRenew:()=>void;onOpenRecovery:()=>void;onClearCopies:()=>void;onRestore:(raw:string)=>void;onImport:()=>void;onDownloadOriginal:()=>void};
export default function DataManagement(p:Props & {state?:AppState;onRemoveOrphan?:(item:OrphanItem)=>Promise<void>}){
  const [showReviewed,setShowReviewed]=useState(false);
  const [showCopies,setShowCopies]=useState(false);
  const disabled=p.busy||!p.canEdit;
  return <section className="space-y-4">
    <header><h2 className="text-xl font-bold">Dades i desat</h2><p className="text-sm text-slate-600">Treballa en diverses pestanyes del mateix navegador. Els canvis compatibles es combinen i les altres pestanyes s’actualitzen automàticament.</p></header>
    <section className="ds-panel space-y-3"><h3 className="font-semibold">Estat del desat</h3><p role="status" aria-live="polite" className={p.status==='error'?'text-rose-700':p.status==='saving'?'text-amber-700':'text-emerald-700'}>{p.status==='saved'?'Desat':p.status==='saving'?'Desant…':'Hi ha canvis o un desat pendents de resoldre'} · {p.linkedFileName?`Navegador i ${p.linkedFileName}`:'Navegador'}</p><div className="flex flex-wrap gap-2"><button className="ds-button" disabled={disabled} onClick={p.onRetry}>Tornar a desar</button><button className="ds-button" onClick={p.onDownload}>Descarregar JSON d’aquesta pestanya</button><button className="ds-button" onClick={p.onDownloadOriginal}>Descarregar versió compartida</button><button className="ds-button" disabled={disabled} onClick={p.onImport}>Importar JSON</button></div>{!p.canEdit&&<p className="text-amber-800">Aquest navegador no admet la coordinació entre pestanyes. Pots consultar i descarregar les dades.</p>}</section>
    {p.status==='error'&&<section className="ds-panel space-y-3 border-rose-300"><h3 className="font-semibold">Resoldre el desat pendent</h3><p>Els canvis d’aquesta pestanya es mantenen en memòria. Descarrega’ls abans de descartar-los.</p>{p.conflicts.length>0&&<><p>Les dues versions han modificat aquests camps:</p><ul className="list-disc pl-5 max-h-48 overflow-auto">{p.conflicts.map((x,i)=><li key={i} className="break-all">{x}</li>)}</ul><button className="ds-button" disabled={disabled} onClick={p.onKeepLocal}>Aplicar els meus canvis als camps en conflicte</button></>}<button className="ds-button" disabled={disabled} onClick={p.onDiscard}>Descartar els meus pendents i carregar la versió compartida</button></section>}
    {p.state&&p.onRemoveOrphan&&<OrphanDataReview state={p.state} disabled={disabled||p.status!=='saved'} onRemove={p.onRemoveOrphan}/>}
    <section className="ds-panel space-y-3"><div className="flex justify-between gap-3"><h3 className="font-semibold">Avisos</h3><label className="text-sm"><input type="checkbox" checked={showReviewed} onChange={e=>setShowReviewed(e.target.checked)}/> Mostrar també els revisats</label></div><p className="text-sm text-slate-500">Marcar un avís com a revisat evita que torni a destacar al menú. No elimina dades ni dona per resolt un desat fallit.</p>{p.notices.filter(n=>showReviewed||!p.reviewed.includes(n.key)).map(n=><article key={n.key} className="border-t pt-3 space-y-2"><p className="whitespace-pre-wrap break-words text-sm">{n.message}</p>{p.reviewed.includes(n.key)?<span className="text-xs text-slate-500">Revisat</span>:<button className="ds-button" onClick={()=>p.onReview(n.key)}>Acceptar i no tornar a destacar aquest avís</button>}</article>)}{!p.notices.some(n=>!p.reviewed.includes(n.key))&&<p className="text-sm text-slate-500">No hi ha avisos nous.</p>}</section>
    <section className="ds-panel space-y-3"><h3 className="font-semibold">Fitxer enllaçat</h3><p>{p.linkedFileName?`Desat al fitxer: ${p.linkedFileName}`:p.availableName?`Fitxer recordat: ${p.availableName}. Es conserven les dades del navegador fins que decideixis què fer.`:'S’utilitzen les dades compartides del navegador.'}</p><div className="flex flex-wrap gap-2"><button className="ds-button" disabled={disabled} onClick={p.onChooseFile}>Seleccionar fitxer</button>{p.availableName&&<><button className="ds-button" disabled={disabled} onClick={p.onConnect}>Carregar el fitxer i enllaçar-lo</button><button className="ds-button" disabled={disabled} onClick={p.onKeepCurrent}>Enllaçar conservant les dades compartides</button></>}{p.linkedFileName&&<button className="ds-button" disabled={disabled} onClick={p.onRenew}>Renovar permís i tornar a desar</button>}{(p.availableName||p.linkedFileName)&&<button className="ds-button" disabled={disabled} onClick={p.onForget}>Oblidar l’enllaç i continuar al navegador</button>}</div><p className="text-xs text-slate-500">Oblidar l’enllaç no esborra el fitxer ni les notes. Deixa de recordar-lo a totes les pestanyes. Si havia fallat el desat al fitxer, prem després «Tornar a desar».</p></section>
    <section className="ds-panel space-y-3"><h3 className="font-semibold">Còpies recuperables</h3><button className="ds-button" onClick={()=>{p.onOpenRecovery();setShowCopies(true);}}>Consultar còpies</button>{showCopies&&p.copies.map(c=><div key={c.id} className="flex flex-wrap gap-2 items-center border-t pt-2"><span className="text-sm">{new Date(c.date).toLocaleString('ca')} · {c.reason}</span><button className="ds-button" onClick={()=>triggerRawJsonDownload(c.raw,`recuperacio_${c.id}.json`)}>Descarregar</button><button className="ds-button" disabled={disabled} onClick={()=>{if(confirm('Restaurar aquesta còpia a totes les pestanyes? Es conservarà la versió actual.'))p.onRestore(c.raw);}}>Restaurar</button></div>)}<div><button className="ds-button" disabled={disabled} onClick={p.onClearCopies}>Arxivar i eliminar còpies del navegador</button><p className="text-xs text-slate-500 mt-2">Permet alliberar espai o eliminar un registre de còpies malmès. Primer es descarrega l’arxiu de còpies. No esborra les dades actives.</p></div></section>
  </section>;
}
