import React,{useState} from 'react';
import {UserCheck,BookOpen} from 'lucide-react';
import {sessionIndicators} from '../utils/sessionIndicators';
import {AppState} from '../types';
import {getMonday,getWeekDays,toIsoDate,formatCatalanShortDate,getHolidayForDate,getTermForDate,getOngoingActivitiesForSession,getLastDayBeforeDeliveryActivities} from '../utils/dateHelpers';
import {getDayBlocks,timetableSettings,minutes,clock} from '../utils/sessionBlocks';

type Props={state:AppState;onSelectSession:(id:string,date:string)=>void;onNavigateToConfig:()=>void;onChangeState:(state:AppState,base?:AppState)=>boolean|void};
const days=['Dilluns','Dimarts','Dimecres','Dijous','Divendres'];
export default function HorariView({state,onSelectSession}:Props){
  const [currentDate,setCurrentDate]=useState(()=>new Date());
  const config=timetableSettings(state);
  const week=getWeekDays(getMonday(new Date(currentDate)));
  const shift=(n:number)=>{const d=new Date(currentDate);d.setDate(d.getDate()+n);setCurrentDate(d);};
  const columns=week.map(date=>{const iso=toIsoDate(date);return {iso,holiday:getHolidayForDate(iso,state.config.holidays),term:getTermForDate(iso,state.config.terms),blocks:getDayBlocks(state,iso)};});
  const timed=columns.flatMap(c=>c.blocks).filter(b=>Number.isFinite(minutes(b.startTime))&&Number.isFinite(minutes(b.endTime))&&minutes(b.endTime)>minutes(b.startTime));
  const start=Math.min(minutes(config.startTime),...timed.map(b=>minutes(b.startTime)));
  const end=Math.max(minutes(config.endTime),...timed.map(b=>minutes(b.endTime)));
  const scale=1.6,height=(end-start)*scale;
  const ticks:number[]=[];for(let t=start;t<end;t+=config.slotMinutes)ticks.push(t);ticks.push(end);
  return <section id="horari-view-root" className="space-y-3"><header className="page-heading flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Horari de classes</h2><p className="text-sm text-slate-500">{formatCatalanShortDate(columns[0].iso)} – {formatCatalanShortDate(columns[4].iso)}</p></div><div className="flex gap-2 flex-wrap"><button className="ds-button" aria-label="Setmana anterior" onClick={()=>shift(-7)}>←</button><button className="ds-button" onClick={()=>setCurrentDate(new Date())}>Avui</button><button className="ds-button" aria-label="Setmana següent" onClick={()=>shift(7)}>→</button></div></header>
    {(start<minutes(config.startTime)||end>minutes(config.endTime))&&<p className="text-sm text-amber-800">S’ha ampliat la vista per mostrar activitats fora de l’interval configurat.</p>}
    <div className="overflow-auto rounded-xl border bg-white"><div style={{minWidth:850}}><div className="grid sticky top-0 z-20 bg-slate-50 border-b" style={{gridTemplateColumns:'72px repeat(5,minmax(0,1fr))'}}><div className="p-2 text-xs">Hora</div>{columns.map((c,i)=><div key={c.iso} className="p-2 border-l"><b>{days[i]}</b><span className="block text-xs">{formatCatalanShortDate(c.iso)}</span><span className="block text-xs text-sky-700">{c.term?.name}</span>{c.holiday&&<span className="text-xs text-amber-800">{c.holiday.label}</span>}</div>)}</div>
    <div className="grid" style={{gridTemplateColumns:'72px repeat(5,minmax(0,1fr))'}}><div className="relative bg-slate-50 text-xs text-slate-500" style={{height:height+24}}>{ticks.map(t=><span key={t} className="absolute right-2" style={{top:(t-start)*scale}}>{clock(t)}</span>)}</div>{columns.map(c=><div key={c.iso} className={'relative border-l '+(c.iso===toIsoDate(new Date())?'bg-sky-50/30':'')} style={{height:height+24}}>
      {ticks.map(t=><div key={t} className="absolute inset-x-0 border-t border-slate-100" style={{top:(t-start)*scale}}/>)}
      {c.holiday?<p className="p-3 text-sm text-amber-800">Festiu · {c.holiday.label}</p>:c.iso<state.config.startDate||c.iso>state.config.endDate?<p className="p-3 text-sm text-slate-400">Fora del calendari lectiu</p>:c.blocks.filter(b=>Number.isFinite(minutes(b.startTime))&&Number.isFinite(minutes(b.endTime))&&minutes(b.endTime)>minutes(b.startTime)).map(b=>{
        const subject=state.subjects.find(s=>s.id===b.subjectId);
        const indicator=sessionIndicators(state,b,c.iso);
        const ongoing=getOngoingActivitiesForSession(state,b.subjectId,c.iso),due=getLastDayBeforeDeliveryActivities(state,b.subjectId,c.iso);
        const overlaps=c.blocks.filter(x=>minutes(x.startTime)<minutes(b.endTime)&&minutes(x.endTime)>minutes(b.startTime));const lane=overlaps.findIndex(x=>x.id===b.id),lanes=overlaps.length||1;
        return <article key={b.id} className="absolute rounded-lg border bg-white overflow-hidden shadow-sm flex flex-col" style={{top:(minutes(b.startTime)-start)*scale,height:(minutes(b.endTime)-minutes(b.startTime))*scale-2,left:`calc(${lane*100/lanes}% + 2px)`,width:`calc(${100/lanes}% - 4px)`,borderLeft:'4px solid '+(subject?.color||'#64748b')}}><button className="text-left p-2 flex-1 min-h-0 overflow-hidden" disabled={!subject} onClick={()=>onSelectSession(b.id,c.iso)} title={(subject?.name||b.reason||'Assignatura inexistent')+' · '+b.startTime+'–'+b.endTime}><b className="block text-sm">{subject?.name||b.reason||'Assignatura inexistent'}</b><span className="block text-xs">{b.startTime}–{b.endTime}</span>{indicator.notHeld&&<span className="text-xs font-semibold text-amber-800 block" title={indicator.notHeldReason||'Sense motiu indicat'}>⊘ No feta</span>}{b.substitution&&<span className="text-xs">Substitució</span>}{b.memberIds.length>1&&<span className="text-xs block">Registre únic · {b.memberIds.length} franges</span>}{indicator.recorded>0&&<span className={'inline-flex align-middle mr-2 '+(indicator.complete?'text-emerald-700':'text-amber-700')} title={(indicator.complete?'Assistència passada':'Assistència parcial')+' · '+indicator.recorded+'/'+indicator.total+' alumnes'} aria-label={(indicator.complete?'Assistència passada':'Assistència parcial')+' · '+indicator.recorded+'/'+indicator.total+' alumnes'}><UserCheck className="w-4 h-4" aria-hidden="true"/></span>}{indicator.hasDiary&&<span className="inline-flex align-middle mr-2 text-blue-700" title="Diari d’aquesta sessió amb anotacions" aria-label="Diari d’aquesta sessió amb anotacions"><BookOpen className="w-4 h-4" aria-hidden="true"/></span>}{ongoing.length>0&&<span className="mr-2" title={ongoing.map(a=>a.title).join('\n')} aria-label="Activitats en curs">📋</span>}{due.length>0&&<span title={due.map(a=>a.title).join('\n')} aria-label="Última sessió abans del lliurament">⏳</span>}</button></article>;
      })}
    </div>)}</div></div></div>
    {columns.some(c=>c.blocks.some(b=>!Number.isFinite(minutes(b.startTime))||!Number.isFinite(minutes(b.endTime))||minutes(b.endTime)<=minutes(b.startTime)))&&<section className="ds-panel"><h3 className="font-bold">Entrades pendents de definir l’hora</h3><p className="text-sm text-slate-500">Defineix les hores a Configuració → Calendari → Franges i Horari.</p>{columns.flatMap((c,i)=>c.blocks.filter(b=>!Number.isFinite(minutes(b.startTime))||!Number.isFinite(minutes(b.endTime))||minutes(b.endTime)<=minutes(b.startTime)).map(b=><div key={c.iso+b.id} className="flex gap-3 py-1"><span>{days[i]} · {state.subjects.find(s=>s.id===b.subjectId)?.name||b.reason||b.id}</span><button className="ds-button" disabled={!b.subjectId} onClick={()=>onSelectSession(b.id,c.iso)}>Obrir registre</button></div>))}</section>}
    <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-600" aria-label="Llegenda dels indicadors"><span className="inline-flex items-center gap-1"><UserCheck className="w-4 h-4 text-emerald-700" aria-hidden="true"/>Assistència passada</span><span className="inline-flex items-center gap-1"><UserCheck className="w-4 h-4 text-amber-700" aria-hidden="true"/>Assistència parcial</span><span className="inline-flex items-center gap-1"><BookOpen className="w-4 h-4 text-blue-700" aria-hidden="true"/>Diari amb anotacions</span></div>
    <p className="text-xs text-slate-500">Un bloc equival a una sessió d’assistència, independentment de la durada. Una pausa, un altre grup o una substitució separen els blocs.</p>
  </section>;
}

