import React,{useState} from 'react';
import {AppState} from '../types';
import {getMonday,getWeekDays,toIsoDate,formatCatalanShortDate,getHolidayForDate,getTermForDate,getOngoingActivitiesForSession,getLastDayBeforeDeliveryActivities} from '../utils/dateHelpers';
import {getDayBlocks,timetableSettings,saveTimetableEntry,minutes,clock} from '../utils/sessionBlocks';

type Props={state:AppState;onSelectSession:(id:string,date:string)=>void;onNavigateToConfig:()=>void;onChangeState:(state:AppState,base?:AppState)=>boolean|void};
type Draft={base:AppState;id?:string;subjectId:string;dayOfWeek:number;startTime:string;endTime:string};
const days=['Dilluns','Dimarts','Dimecres','Dijous','Divendres'];
export default function HorariView({state,onSelectSession,onNavigateToConfig,onChangeState}:Props){
  const [currentDate,setCurrentDate]=useState(()=>new Date());
  const [draft,setDraft]=useState<Draft|null>(null);
  const [settings,setSettings]=useState<({base:AppState}&ReturnType<typeof timetableSettings>)|null>(null);
  const [editing,setEditing]=useState<string[]|null>(null);
  const [error,setError]=useState('');
  const config=timetableSettings(state);
  const week=getWeekDays(getMonday(new Date(currentDate)));
  const subjects=state.subjects.filter(s=>!s.isParent);
  const back=()=>{setDraft(null);setSettings(null);setEditing(null);setError('');};
  const edit=(id:string)=>{const item=state.schedule.find(s=>s.id===id);if(!item)return;const slot=state.config.timeSlots.find(s=>s.id===item.timeSlotId);setError('');setDraft({base:state,id,subjectId:item.subjectId,dayOfWeek:item.dayOfWeek,startTime:slot?.startTime||config.startTime,endTime:slot?.endTime||clock(Math.min(minutes(config.startTime)+60,1439))});};
  const heading=(title:string)=><header className="page-heading flex justify-between items-center"><h2 className="text-xl font-bold">{title}</h2><button className="ds-button" onClick={back}>Tornar a l’horari</button></header>;
  if(settings)return <section className="space-y-4">{heading('Configurar la vista d’horari')}<form className="ds-panel space-y-4" onSubmit={e=>{e.preventDefault();if(minutes(settings.endTime)<=minutes(settings.startTime)){setError('L’hora final ha de ser posterior a la inicial.');return;}const {base,...values}=settings;try{if(onChangeState({...base,config:{...base.config,timetable:values}},base)!==false)back();}catch(e){setError((e as Error).message);}}}><div className="grid sm:grid-cols-3 gap-4"><label className="ds-field">Hora d’inici<input required type="time" value={settings.startTime} onChange={e=>setSettings({...settings,startTime:e.target.value})}/></label><label className="ds-field">Hora de fi<input required type="time" value={settings.endTime} onChange={e=>setSettings({...settings,endTime:e.target.value})}/></label><label className="ds-field">Minuts de les franges<input required type="number" min={5} max={120} step={1} value={settings.slotMinutes} onChange={e=>setSettings({...settings,slotMinutes:Number(e.target.value)})}/></label></div><p className="text-sm text-slate-500">Les franges només divideixen la vista. No canvien la durada de les activitats ni esborren registres. Una activitat pot començar i acabar entre divisions.</p>{error&&<p role="alert" className="text-rose-700">{error}</p>}<button className="ds-button" type="submit">Desar vista d’horari</button></form></section>;
  if(draft)return <section className="space-y-4">{heading(draft.id?'Editar activitat docent':'Nova activitat docent')}<form className="ds-panel space-y-4" onSubmit={e=>{e.preventDefault();try{const {base,...input}=draft;if(onChangeState(saveTimetableEntry(base,input),base)!==false)back();}catch(e){setError((e as Error).message);}}}>
    <div className="grid sm:grid-cols-2 gap-4"><label className="ds-field">Assignatura / acció docent<select required value={draft.subjectId} onChange={e=>setDraft({...draft,subjectId:e.target.value})}><option value="" disabled>Selecciona…</option>{subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label className="ds-field">Dia de la setmana<select value={draft.dayOfWeek} onChange={e=>setDraft({...draft,dayOfWeek:Number(e.target.value)})}>{days.map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><label className="ds-field">Hora d’inici<input required type="time" value={draft.startTime} onChange={e=>{const start=e.target.value;setDraft({...draft,startTime:start,endTime:!draft.id&&Number.isFinite(minutes(start))?clock(Math.min(minutes(start)+60,1439)):draft.endTime});}}/></label><label className="ds-field">Hora de fi<input required type="time" value={draft.endTime} onChange={e=>setDraft({...draft,endTime:e.target.value})}/></label></div>
    <p className="text-sm text-slate-500">Es repeteix setmanalment dins del calendari lectiu. Durada inicial: una hora. Les activitats consecutives de la mateixa assignatura o acció docent es mostren com un únic bloc.</p>
    {error&&<p role="alert" className="text-rose-700">{error}</p>}<button className="ds-button" type="submit">Desar activitat docent</button></form></section>;
  if(editing)return <section className="space-y-4">{heading('Editar les hores del bloc')}<p>Aquest bloc agrupa entrades consecutives de l’horari anterior. Pots ajustar cada entrada; els registres existents es conserven.</p>{editing.map(id=>{const item=state.schedule.find(s=>s.id===id),slot=state.config.timeSlots.find(s=>s.id===item?.timeSlotId);return <div className="ds-panel flex justify-between" key={id}><span>{slot?.startTime}–{slot?.endTime}</span><button className="ds-button" onClick={()=>edit(id)}>Editar aquesta entrada</button></div>;})}</section>;
  const shift=(n:number)=>{const d=new Date(currentDate);d.setDate(d.getDate()+n);setCurrentDate(d);};
  const columns=week.map(date=>{const iso=toIsoDate(date);return {iso,holiday:getHolidayForDate(iso,state.config.holidays),term:getTermForDate(iso,state.config.terms),blocks:getDayBlocks(state,iso)};});
  const timed=columns.flatMap(c=>c.blocks).filter(b=>Number.isFinite(minutes(b.startTime))&&Number.isFinite(minutes(b.endTime))&&minutes(b.endTime)>minutes(b.startTime));
  const start=Math.min(minutes(config.startTime),...timed.map(b=>minutes(b.startTime)));
  const end=Math.max(minutes(config.endTime),...timed.map(b=>minutes(b.endTime)));
  const scale=1.6,height=(end-start)*scale;
  const ticks:number[]=[];for(let t=start;t<end;t+=config.slotMinutes)ticks.push(t);ticks.push(end);
  return <section id="horari-view-root" className="space-y-3"><header className="page-heading flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Horari de classes</h2><p className="text-sm text-slate-500">{formatCatalanShortDate(columns[0].iso)} – {formatCatalanShortDate(columns[4].iso)}</p></div><div className="flex gap-2 flex-wrap"><button className="ds-button" aria-label="Setmana anterior" onClick={()=>shift(-7)}>←</button><button className="ds-button" onClick={()=>setCurrentDate(new Date())}>Avui</button><button className="ds-button" aria-label="Setmana següent" onClick={()=>shift(7)}>→</button><button className="ds-button" onClick={()=>{setError('');setSettings({base:state,...config});}}>Configurar vista</button><button className="ds-button" onClick={()=>{setError('');setDraft({base:state,subjectId:subjects[0]?.id||'',dayOfWeek:1,startTime:config.startTime,endTime:clock(Math.min(minutes(config.startTime)+60,1439))});}}>Nova activitat docent</button><button className="ds-button" onClick={onNavigateToConfig}>Configuració del curs</button></div></header>
    {(start<minutes(config.startTime)||end>minutes(config.endTime))&&<p className="text-sm text-amber-800">S’ha ampliat la vista per mostrar activitats fora de l’interval configurat.</p>}
    <div className="overflow-auto rounded-xl border bg-white"><div style={{minWidth:850}}><div className="grid sticky top-0 z-20 bg-slate-50 border-b" style={{gridTemplateColumns:'72px repeat(5,minmax(0,1fr))'}}><div className="p-2 text-xs">Hora</div>{columns.map((c,i)=><div key={c.iso} className="p-2 border-l"><b>{days[i]}</b><span className="block text-xs">{formatCatalanShortDate(c.iso)}</span><span className="block text-xs text-sky-700">{c.term?.name}</span>{c.holiday&&<span className="text-xs text-amber-800">{c.holiday.label}</span>}</div>)}</div>
    <div className="grid" style={{gridTemplateColumns:'72px repeat(5,minmax(0,1fr))'}}><div className="relative bg-slate-50 text-xs text-slate-500" style={{height:height+24}}>{ticks.map(t=><span key={t} className="absolute right-2" style={{top:(t-start)*scale}}>{clock(t)}</span>)}</div>{columns.map(c=><div key={c.iso} className={'relative border-l '+(c.iso===toIsoDate(new Date())?'bg-sky-50/30':'')} style={{height:height+24}}>
      {ticks.map(t=><div key={t} className="absolute inset-x-0 border-t border-slate-100" style={{top:(t-start)*scale}}/>)}
      {c.holiday?<p className="p-3 text-sm text-amber-800">Festiu · {c.holiday.label}</p>:c.iso<state.config.startDate||c.iso>state.config.endDate?<p className="p-3 text-sm text-slate-400">Fora del calendari lectiu</p>:c.blocks.filter(b=>Number.isFinite(minutes(b.startTime))&&Number.isFinite(minutes(b.endTime))&&minutes(b.endTime)>minutes(b.startTime)).map(b=>{
        const subject=state.subjects.find(s=>s.id===b.subjectId);
        const ongoing=getOngoingActivitiesForSession(state,b.subjectId,c.iso),due=getLastDayBeforeDeliveryActivities(state,b.subjectId,c.iso);
        const overlaps=c.blocks.filter(x=>minutes(x.startTime)<minutes(b.endTime)&&minutes(x.endTime)>minutes(b.startTime));const lane=overlaps.findIndex(x=>x.id===b.id),lanes=overlaps.length||1;
        return <article key={b.id} className="absolute rounded-lg border bg-white overflow-hidden shadow-sm flex flex-col" style={{top:(minutes(b.startTime)-start)*scale,height:(minutes(b.endTime)-minutes(b.startTime))*scale-2,left:`calc(${lane*100/lanes}% + 2px)`,width:`calc(${100/lanes}% - 4px)`,borderLeft:'4px solid '+(subject?.color||'#64748b')}}><button className="text-left p-2 flex-1 min-h-0 overflow-hidden" disabled={!subject} onClick={()=>onSelectSession(b.id,c.iso)} title={(subject?.name||b.reason||'Assignatura inexistent')+' · '+b.startTime+'–'+b.endTime}><b className="block text-sm">{subject?.name||b.reason||'Assignatura inexistent'}</b><span className="block text-xs">{b.startTime}–{b.endTime}</span>{b.substitution&&<span className="text-xs">Substitució</span>}{b.memberIds.length>1&&<span className="text-xs block">Registre únic · {b.memberIds.length} franges</span>}{ongoing.length>0&&<span className="mr-2" title={ongoing.map(a=>a.title).join('\n')} aria-label="Activitats en curs">📋</span>}{due.length>0&&<span title={due.map(a=>a.title).join('\n')} aria-label="Última sessió abans del lliurament">⏳</span>}</button>{!b.substitution&&<button className="text-xs text-sky-800 border-t py-1" onClick={()=>b.memberIds.length>1?setEditing(b.memberIds):edit(b.id)}>Editar</button>}</article>;
      })}
    </div>)}</div></div></div>
    {columns.some(c=>c.blocks.some(b=>!Number.isFinite(minutes(b.startTime))||!Number.isFinite(minutes(b.endTime))||minutes(b.endTime)<=minutes(b.startTime)))&&<section className="ds-panel"><h3 className="font-bold">Entrades pendents de definir l’hora</h3>{columns.flatMap((c,i)=>c.blocks.filter(b=>!Number.isFinite(minutes(b.startTime))||!Number.isFinite(minutes(b.endTime))||minutes(b.endTime)<=minutes(b.startTime)).map(b=><div key={c.iso+b.id} className="flex gap-3 py-1"><span>{days[i]} · {state.subjects.find(s=>s.id===b.subjectId)?.name||b.reason||b.id}</span><button className="ds-button" disabled={!b.subjectId} onClick={()=>onSelectSession(b.id,c.iso)}>Obrir registre</button>{!b.substitution&&<button className="ds-button" onClick={()=>edit(b.id)}>Definir hores</button>}</div>))}</section>}
    <p className="text-xs text-slate-500">Un bloc equival a una sessió d’assistència, independentment de la durada. Una pausa, un altre grup o una substitució separen els blocs.</p>
  </section>;
}
