import React,{useState} from 'react';
import {AppState,Student} from '../types';
import {updateStudentNames} from '../utils/studentNames';

export default function StudentNamesEditor({state,student,onChange,children}:{state:AppState;student:Student;onChange:(state:AppState,base?:AppState)=>boolean|void;children?:React.ReactNode}){
  const [draft,setDraft]=useState<{base:AppState;name:string;preferredName:string}|null>(null);
  const [error,setError]=useState('');
  return <section className="ds-panel space-y-3"><div className="flex justify-between items-center gap-2"><h3 className="font-bold">Nom de l’alumne</h3><div className="flex flex-col items-end gap-2">{!draft&&<button className="ds-button" onClick={()=>{setError('');setDraft({base:state,name:student.name,preferredName:student.preferredName||''});}}>Editar noms</button>}{children}</div></div>{draft?<form className="space-y-3" onSubmit={e=>{e.preventDefault();try{const next=updateStudentNames(draft.base,student.id,draft.name,draft.preferredName);if(onChange(next,draft.base)!==false)setDraft(null);}catch(e){setError((e as Error).message);}}}><div className="grid md:grid-cols-2 gap-3"><label className="ds-field">Nom oficial i cognoms<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="ds-field">Nom d’ús habitual (opcional)<input value={draft.preferredName} placeholder="Si és buit, es mostra el nom oficial" onChange={e=>setDraft({...draft,preferredName:e.target.value})}/></label></div><div className="flex gap-2"><button className="ds-button" type="submit">Desar noms</button><button className="ds-button" type="button" onClick={()=>{setDraft(null);setError('');}}>Cancel·lar</button></div></form>:<dl className="grid md:grid-cols-2 gap-3"><div><dt className="text-sm text-slate-500">Nom oficial i cognoms</dt><dd className="font-semibold">{student.name}</dd></div><div><dt className="text-sm text-slate-500">Nom d’ús habitual</dt><dd>{student.preferredName||'Es fa servir el nom oficial'}</dd></div></dl>}<p className="text-xs text-slate-500">Nom oficial: qualificacions i informes. Nom habitual: fitxa, alumnat, diari, assistència i plànols. El canvi s’aplica a totes les assignatures i conserva els registres.</p>{error&&<p role="alert" className="text-rose-700">{error}</p>}</section>;
}

