import React,{useState} from 'react';
import {AppState} from '../types';
import {timetableSettings,saveTimetableEntry,minutes,clock} from '../utils/sessionBlocks';
type Props={state:AppState;onChangeState:(state:AppState,base?:AppState)=>boolean|void};
type Draft={base:AppState;id?:string;subjectId:string;dayOfWeek:number;startTime:string;endTime:string};
const days=['Dilluns','Dimarts','Dimecres','Dijous','Divendres'];
export default function TimetableSettings({state,onChangeState}:Props){
  const [draft,setDraft]=useState<Draft|null>(null);
  const [settings,setSettings]=useState<({base:AppState}&ReturnType<typeof timetableSettings>)|null>(null);
  const [error,setError]=useState('');
  const config=timetableSettings(state);
  const subjects=state.subjects.filter(s=>!s.isParent);
  const back=()=>{setDraft(null);setSettings(null);setError('');};
  const edit=(id:string)=>{const item=state.schedule.find(s=>s.id===id);if(!item)return;const slot=state.config.timeSlots.find(s=>s.id===item.timeSlotId);setError('');setDraft({base:state,id,subjectId:item.subjectId,dayOfWeek:item.dayOfWeek,startTime:slot?.startTime||config.startTime,endTime:slot?.endTime||clock(Math.min(minutes(config.startTime)+60,1439))});};
  const heading=(title:string)=><header className="page-heading flex justify-between items-center"><h2 className="text-xl font-bold">{title}</h2><button className="ds-button" onClick={back}>Tornar a la configuració d’hores</button></header>;
  if(settings)return <section className="space-y-4">{heading('Configurar la vista d’horari')}<form className="ds-panel space-y-4" onSubmit={e=>{e.preventDefault();if(minutes(settings.endTime)<=minutes(settings.startTime)){setError('L’hora final ha de ser posterior a la inicial.');return;}const {base,...values}=settings;try{if(onChangeState({...base,config:{...base.config,timetable:values}},base)!==false)back();}catch(e){setError((e as Error).message);}}}><div className="grid sm:grid-cols-3 gap-4"><label className="ds-field">Hora d’inici<input required type="time" value={settings.startTime} onChange={e=>setSettings({...settings,startTime:e.target.value})}/></label><label className="ds-field">Hora de fi<input required type="time" value={settings.endTime} onChange={e=>setSettings({...settings,endTime:e.target.value})}/></label><label className="ds-field">Minuts de les franges<input required type="number" min={5} max={120} step={1} value={settings.slotMinutes} onChange={e=>setSettings({...settings,slotMinutes:Number(e.target.value)})}/></label></div><p className="text-sm text-slate-500">Les franges només divideixen la vista. No canvien la durada de les activitats ni esborren registres. Una activitat pot començar i acabar entre divisions.</p>{error&&<p role="alert" className="text-rose-700">{error}</p>}<button className="ds-button" type="submit">Desar vista d’horari</button></form></section>;
  if(draft)return <section className="space-y-4">{heading(draft.id?'Editar activitat docent':'Nova activitat docent')}<form className="ds-panel space-y-4" onSubmit={e=>{e.preventDefault();try{const {base,...input}=draft;if(onChangeState(saveTimetableEntry(base,input),base)!==false)back();}catch(e){setError((e as Error).message);}}}>
    <div className="grid sm:grid-cols-2 gap-4"><label className="ds-field">Assignatura / acció docent<select required value={draft.subjectId} onChange={e=>setDraft({...draft,subjectId:e.target.value})}><option value="" disabled>Selecciona…</option>{subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label className="ds-field">Dia de la setmana<select value={draft.dayOfWeek} onChange={e=>setDraft({...draft,dayOfWeek:Number(e.target.value)})}>{days.map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><label className="ds-field">Hora d’inici<input required type="time" value={draft.startTime} onChange={e=>{const start=e.target.value;setDraft({...draft,startTime:start,endTime:!draft.id&&Number.isFinite(minutes(start))?clock(Math.min(minutes(start)+60,1439)):draft.endTime});}}/></label><label className="ds-field">Hora de fi<input required type="time" value={draft.endTime} onChange={e=>setDraft({...draft,endTime:e.target.value})}/></label></div>
    <p className="text-sm text-slate-500">Es repeteix setmanalment dins del calendari lectiu. Durada inicial: una hora. Les activitats consecutives de la mateixa assignatura o acció docent es mostren com un únic bloc.</p>
    {error&&<p role="alert" className="text-rose-700">{error}</p>}<button className="ds-button" type="submit">Desar activitat docent</button></form></section>;

  const entries=[...state.schedule].sort((a,b)=>a.dayOfWeek-b.dayOfWeek||(state.config.timeSlots.find(t=>t.id===a.timeSlotId)?.startTime||'').localeCompare(state.config.timeSlots.find(t=>t.id===b.timeSlotId)?.startTime||''));
  return <section id="panel-hours" className="space-y-4">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">Hores i activitats docents</h3><p className="text-sm text-slate-500">Vista: {config.startTime}–{config.endTime} · divisions de {config.slotMinutes} minuts</p></div><div className="flex flex-wrap gap-2">
      <button className="ds-button" onClick={()=>{setError('');setSettings({base:state,...config});}}>Configurar vista d’horari</button>
      <button className="ds-button ds-primary" onClick={()=>{setError('');setDraft({base:state,subjectId:subjects[0]?.id||'',dayOfWeek:1,startTime:config.startTime,endTime:clock(Math.min(minutes(config.startTime)+60,1439))});}}>Nova activitat docent</button>
    </div></header>
    <p className="text-sm text-slate-500">Gestiona aquí totes les hores. A l’horari, prem un bloc per obrir el registre de classe. Les entrades consecutives de la mateixa assignatura formen un únic bloc.</p>
    <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm text-left"><thead className="bg-slate-100"><tr>{['Dia','Assignatura / acció docent','Inici','Final','Accions'].map(title=><th className="p-3" key={title}>{title}</th>)}</tr></thead><tbody>
      {entries.map(item=>{const subject=state.subjects.find(s=>s.id===item.subjectId),slot=state.config.timeSlots.find(t=>t.id===item.timeSlotId);return <tr key={item.id} className="border-t even:bg-slate-50"><td className="p-3">{days[item.dayOfWeek-1]}</td><td className="p-3">{subject?.name||'Assignatura inexistent'}</td><td className="p-3">{slot?.startTime||'Pendent'}</td><td className="p-3">{slot?.endTime||'Pendent'}</td><td className="p-3"><div className="flex gap-2"><button className="ds-button" onClick={()=>edit(item.id)}>Editar</button><button className="ds-button text-rose-700" onClick={()=>{if(window.confirm('Eliminar de l’horari '+(subject?.name||item.id)+'? Els registres ja desats es conservaran com a històric desvinculat.'))onChangeState({...state,schedule:state.schedule.filter(s=>s.id!==item.id)},state);}}>Eliminar</button></div></td></tr>;})}
      {!entries.length&&<tr><td colSpan={5} className="p-6 text-center text-slate-500">Encara no hi ha activitats docents a l’horari.</td></tr>}
    </tbody></table></div>
  </section>;
}
